name: Generate Behave HTML Report

on:
  push:
    branches: [CICD_pipeline]
  pull_request:
    branches: [CICD_pipeline]

jobs:
  generate-behave-report:
    runs-on: ubuntu-latest  # Or ubuntu-22.04 if the issue persists

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14.0

      - name: Verify Python version
        run: python --version  # Ensure Python 3.10 is correctly installed

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Verify Behave installation
        run: pip show behave  # Check if behave is installed

      - name: Run Behave tests (with Login tag)
        run: behave -t Login  # Running tests with Login tag, adjust as needed
