name: Run Behave Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master  ]

jobs:
  behave-tests:
    runs-on:

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

 #    - name: Set Up Python
 ##       uses: actions/setup-python@v5
 #       with:
 #         python-version: '3.11'  # Use your Python version here

    #  - name: Install Dependencies
     #   run: |
      #    python -m pip install --upgrade pip
       # #  pip install -r requirements.txt
      - name: Run Behave tests
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          behave -f json -o Reports/report.json

      - name: Running Feature
        run: behave









